# Generated by Django 3.2 on 2024-09-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=150)),
                ('vendor_details', models.JSONField(default=dict)),
                ('date', models.DateField(auto_now=True)),
                ('purchaseList', models.JSONField(default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=150)),
                ('vendor_details', models.JSONField(default=dict)),
                ('date', models.DateField(auto_now=True)),
                ('sellsList', models.JSONField(default=dict)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=100)),
                ('GST', models.CharField(max_length=150, unique=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
